# Generated by Django 2.1 on 2019-03-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcharecord',
            name='user',
            field=models.CharField(default='', max_length=30),
        ),
    ]
