# Generated by Django 2.1 on 2019-03-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='category',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
