# Generated by Django 2.1 on 2019-03-18 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_articlemodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='author_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='edit_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='excerpt',
            field=models.TextField(default=''),
        ),
    ]
