# Generated by Django 2.1 on 2019-03-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_articlemodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='edit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
