# Generated by Django 2.1 on 2019-03-31 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20190331_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='edit_time',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
