# Generated by Django 2.1 on 2019-04-04 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_disqusmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='disqusmodel',
            name='c_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
