# Generated by Django 2.1 on 2019-04-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_disqusmodel_c_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disqusmodel',
            name='c_date',
        ),
        migrations.AlterField(
            model_name='disqusmodel',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
