# Generated by Django 2.1 on 2019-04-06 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20190406_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='disqusmodel',
            name='c_time2',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
