# Generated by Django 2.1 on 2019-04-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_disqusmodel_c_time2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disqusmodel',
            name='c_time',
        ),
    ]
