# Generated by Django 2.1 on 2019-04-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_remove_disqusmodel_c_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disqusmodel',
            old_name='c_time2',
            new_name='c_time',
        ),
    ]
