# Generated by Django 2.1 on 2019-04-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_auto_20190406_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='disqusmodel',
            name='color',
            field=models.CharField(default='#ff9911', max_length=8),
        ),
    ]
