# Generated by Django 2.1 on 2019-04-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_disqusmodel_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitModel',
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
