# Generated by Django 2.1 on 2019-04-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20190408_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='cover_img_thumb',
            field=models.CharField(default='', max_length=64),
        ),
    ]
