# Generated by Django 2.1 on 2019-10-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_articlemodel_cover_img_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='extra',
            field=models.TextField(default=''),
        ),
    ]
