# Generated by Django 2.1 on 2019-04-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitmodel',
            name='user_ip_hash',
        ),
        migrations.AddField(
            model_name='visitmodel',
            name='user_ip',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
