# Generated by Django 2.1 on 2019-07-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0003_visitmodel_b_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('page_id', models.IntegerField()),
                ('p_alias', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('extra', models.TextField()),
            ],
        ),
    ]
