# Generated by Django 2.1 on 2019-07-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0004_lifemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifemodel',
            name='extra',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lifemodel',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
