# Generated by Django 2.1 on 2019-10-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0005_auto_20190727_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifemodel',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lifemodel',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
